name: Build and Deploy
env:
  AZURE_WEBAPP_NAME: RevaChat

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch: 

jobs: 
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create Env File
      run: |
      echo "Creating directory"
      mkdir ./AIChat/src/environments
      echo "Creating environment file"
      touch ./AIChat/src/environments/environment.ts
      echo ${{ secrets.ANGULAR_ENVIRONMENT }} >> ./AIChat/src/environments/environment.ts

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.8.0

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.11.0
      with:
        context: ./
        file: .//Dockerfile
        push: true
        tags: index.docker.io/${{ secrets.DOCKER_USER }}/revachat:latest, index.docker.io/${{ secrets.DOCKER_USER }}/revachat:${{ github.sha }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: index.docker.io/${{ secrets.DOCKER_USER }}/revachat:${{ github.sha }}
